// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IContentBlockFields {
  /** Name */
  name: string;

  /** Columns */
  columns: (IImage | IText | IVideo)[];

  /** Background color */
  backgroundColor?: string | undefined;

  /** Text color */
  textColor?: string | undefined;
}

export interface IContentBlock extends Entry<IContentBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "contentBlock";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHeroBlockFields {
  /** Name */
  name?: string | undefined;

  /** Title */
  title: string;

  /** Image */
  image: Asset;
}

export interface IHeroBlock extends Entry<IHeroBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "heroBlock";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IImageFields {
  /** Name */
  name?: string | undefined;

  /** Size */
  size: number;

  /** Image */
  image: Asset;
}

export interface IImage extends Entry<IImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "image";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageFields {
  /** Is Front Page */
  isFrontPage?: boolean | undefined;

  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Content */
  content?: string | undefined;

  /** Blocks */
  blocks?: (IContentBlock | IHeroBlock | IProjectBlock)[] | undefined;
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "page";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPostFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Blocks */
  blocks?: (IContentBlock | IHeroBlock)[] | undefined;
}

export interface IPost extends Entry<IPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "post";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITextFields {
  /** Name */
  name: string;

  /** Size */
  size: number;

  /** Content */
  content: string;
}

export interface IText extends Entry<ITextFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "text";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideoFields {
  /** Name */
  name: string;

  /** Size */
  size: number;

  /** Video */
  video: Asset;
}

export interface IVideo extends Entry<IVideoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "video";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "contentBlock"
  | "heroBlock"
  | "image"
  | "page"
  | "post"
  | "text"
  | "video";

export type LOCALE_CODE = "en" | "sv";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en";
